//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomOtdel.ModelSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainInfo
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string ServiceNote { get; set; }
        public Nullable<int> idPhotoEmployee { get; set; }
        public int idAdditionalInformation { get; set; }
        public Nullable<int> idPassport { get; set; }
        public Nullable<int> idEmploymentRecord { get; set; }
        public Nullable<int> idWorkSchedule { get; set; }
        public Nullable<int> idSalary { get; set; }
        public Nullable<int> idEmployeeStatus { get; set; }
    
        public virtual AdditionalInformation AdditionalInformation { get; set; }
        public virtual EmployeeStatus EmployeeStatus { get; set; }
        public virtual EmploymentRecord EmploymentRecord { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual PhotoEmployee PhotoEmployee { get; set; }
        public virtual Salary Salary { get; set; }
        public virtual WorkSchedule WorkSchedule { get; set; }
    }
}
